export const COUNTRIES = [
  { value: "us", label: "United States", flag: "🇺🇸", fallback: "US" },
  { value: "gb", label: "United Kingdom", flag: "🇬🇧", fallback: "GB" },
  { value: "ca", label: "Canada", flag: "🇨🇦", fallback: "CA" },
  { value: "au", label: "Australia", flag: "🇦🇺", fallback: "AU" },
  { value: "de", label: "Germany", flag: "🇩🇪", fallback: "DE" },
  { value: "fr", label: "France", flag: "🇫🇷", fallback: "FR" },
  { value: "jp", label: "Japan", flag: "🇯🇵", fallback: "JP" },
  { value: "cn", label: "China", flag: "🇨🇳", fallback: "CN" },
  { value: "in", label: "India", flag: "🇮🇳", fallback: "IN" },
  { value: "br", label: "Brazil", flag: "🇧🇷", fallback: "BR" },
  { value: "mx", label: "Mexico", flag: "🇲🇽", fallback: "MX" },
  { value: "es", label: "Spain", flag: "🇪🇸", fallback: "ES" },
  { value: "it", label: "Italy", flag: "🇮🇹", fallback: "IT" },
  { value: "ng", label: "Nigeria", flag: "🇳🇬", fallback: "NG" },
  { value: "za", label: "South Africa", flag: "🇿🇦", fallback: "ZA" },
  { value: "kr", label: "South Korea", flag: "🇰🇷", fallback: "KR" },
  { value: "nl", label: "Netherlands", flag: "🇳🇱", fallback: "NL" },
  { value: "se", label: "Sweden", flag: "🇸🇪", fallback: "SE" },
  { value: "ch", label: "Switzerland", flag: "🇨🇭", fallback: "CH" },
  { value: "sg", label: "Singapore", flag: "🇸🇬", fallback: "SG" },
];
